# Site settings
name: Samuel Johnson
title: Scientist / Engineer - SD
# email: my short first name (six letters) at ISROâ€™s domain (isro [dot] gov [dot] in)
organisation: Indian Space Research Organisation
username: samueljohnson
description: "This page is created using git, jekyll, markdown, vim and other open-source software."
baseurl: ""
url: "samueljohnson.io"

comments :
  provider : disqus
  disqus :
    short_name : samueljohnson

# Build settings
markdown: kramdown
#permalinks: pretty
permalink: /blog/:year/:month/:day/:title/
gems:
          - jekyll-sitemap

theme: jekyll-theme-merlot